apiVersion: v1
kind: ServiceAccount
metadata:
  name: learnk8s-challenge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: learnk8s-challenge
rules:
  - apiGroups: ['', 'apps', 'networking.k8s.io']
    resources: ['pods', 'replicasets', 'services', 'ingresses', 'endpoints']
    verbs: ['list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: learnk8s-challenge
subjects:
  - kind: ServiceAccount
    name: learnk8s-challenge
    apiGroup: ''
    namespace: red
roleRef:
  kind: Role
  name: learnk8s-challenge
  apiGroup: rbac.authorization.k8s.io
